### ISSUE TITLE
IOException : connection failure

### ISSUE THREAD

**Issue by linuxaddict89** [Aptoide/aptoide-client-v8#1432]
Every time i open aptoide it didn't show anything except preloader, only Apps tab work and it seems to me that the problem was on the server.

Aptoide Version : 9.17.20
Log :
```
2020-12-25 12:36:46.764 32175-32324/? E/cm.aptoide.pt.crashreports.ConsoleLogger: Exception found
    java.lang.IllegalStateException: java.io.IOException: Connection failure
        at cm.aptoide.pt.networking.IdsRepository.b(IdsRepository.java:6)
        at cm.aptoide.pt.networking.k.call(Unknown Source:4)
        at rx.n.a.q1$a.a(SingleOnSubscribeMap.java:1)
        at rx.n.e.k$a.a(ScalarSynchronousSingle.java:1)
        at rx.n.e.k$a.call(ScalarSynchronousSingle.java:1)
        at rx.Single.a(Single.java:17)
        at rx.n.a.q1.a(SingleOnSubscribeMap.java:3)
        at rx.n.a.q1.call(SingleOnSubscribeMap.java:1)
        at rx.Single.a(Single.java:17)
        at rx.n.a.i1.a(SingleDoOnEvent.java:3)
        at rx.n.a.i1.call(SingleDoOnEvent.java:1)
        at rx.Single.a(Single.java:17)
        at rx.Single$b$a.call(Single.java:3)
        at rx.n.c.j.run(ScheduledAction.java:2)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.IOException: Connection failure
        at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(Unknown Source:73)
        at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(Unknown Source:17)
        at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(Unknown Source:47)
        at cm.aptoide.pt.networking.IdsRepository.b(IdsRepository.java:4)
        at cm.aptoide.pt.networking.k.call(Unknown Source:4) 
        at rx.n.a.q1$a.a(SingleOnSubscribeMap.java:1) 
        at rx.n.e.k$a.a(ScalarSynchronousSingle.java:1) 
        at rx.n.e.k$a.call(ScalarSynchronousSingle.java:1) 
        at rx.Single.a(Single.java:17) 
        at rx.n.a.q1.a(SingleOnSubscribeMap.java:3) 
        at rx.n.a.q1.call(SingleOnSubscribeMap.java:1) 
        at rx.Single.a(Single.java:17) 
        at rx.n.a.i1.a(SingleDoOnEvent.java:3) 
        at rx.n.a.i1.call(SingleDoOnEvent.java:1) 
        at rx.Single.a(Single.java:17) 
        at rx.Single$b$a.call(Single.java:3) 
        at rx.n.c.j.run(ScheduledAction.java:2) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: null
        at rx.n.a.q1$a.a(SingleOnSubscribeMap.java:5)
        at rx.n.e.k$a.a(ScalarSynchronousSingle.java:1) 
        at rx.n.e.k$a.call(ScalarSynchronousSingle.java:1) 
        at rx.Single.a(Single.java:17) 
        at rx.n.a.q1.a(SingleOnSubscribeMap.java:3) 
        at rx.n.a.q1.call(SingleOnSubscribeMap.java:1) 
        at rx.Single.a(Single.java:17) 
        at rx.n.a.i1.a(SingleDoOnEvent.java:3) 
        at rx.n.a.i1.call(SingleDoOnEvent.java:1) 
        at rx.Single.a(Single.java:17) 
        at rx.Single$b$a.call(Single.java:3) 
        at rx.n.c.j.run(ScheduledAction.java:2) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
2020-12-25 12:36:47.337 32175-777/? E/cm.aptoide.pt.crashreports.ConsoleLogger: Exception found
    java.lang.IllegalStateException: java.io.IOException: Connection failure
        at cm.aptoide.pt.networking.IdsRepository.b(IdsRepository.java:6)
        at cm.aptoide.pt.networking.k.call(Unknown Source:4)
        at rx.n.a.q1$a.a(SingleOnSubscribeMap.java:1)
        at rx.n.e.k$a.a(ScalarSynchronousSingle.java:1)
        at rx.n.e.k$a.call(ScalarSynchronousSingle.java:1)
        at rx.Single.a(Single.java:17)
        at rx.n.a.q1.a(SingleOnSubscribeMap.java:3)
        at rx.n.a.q1.call(SingleOnSubscribeMap.java:1)
        at rx.Single.a(Single.java:17)
        at rx.n.a.i1.a(SingleDoOnEvent.java:3)
        at rx.n.a.i1.call(SingleDoOnEvent.java:1)
        at rx.Single.a(Single.java:17)
        at rx.Single$b$a.call(Single.java:3)
        at rx.n.c.j.run(ScheduledAction.java:2)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.IOException: Connection failure
        at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(Unknown Source:73)
        at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(Unknown Source:17)
        at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(Unknown Source:47)
        at cm.aptoide.pt.networking.IdsRepository.b(IdsRepository.java:4)
        at cm.aptoide.pt.networking.k.call(Unknown Source:4) 
        at rx.n.a.q1$a.a(SingleOnSubscribeMap.java:1) 
        at rx.n.e.k$a.a(ScalarSynchronousSingle.java:1) 
        at rx.n.e.k$a.call(ScalarSynchronousSingle.java:1) 
        at rx.Single.a(Single.java:17) 
        at rx.n.a.q1.a(SingleOnSubscribeMap.java:3) 
        at rx.n.a.q1.call(SingleOnSubscribeMap.java:1) 
        at rx.Single.a(Single.java:17) 
        at rx.n.a.i1.a(SingleDoOnEvent.java:3) 
        at rx.n.a.i1.call(SingleDoOnEvent.java:1) 
        at rx.Single.a(Single.java:17) 
        at rx.Single$b$a.call(Single.java:3) 
        at rx.n.c.j.run(ScheduledAction.java:2) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: null
        at rx.n.a.q1$a.a(SingleOnSubscribeMap.java:5)
        at rx.n.e.k$a.a(ScalarSynchronousSingle.java:1) 
        at rx.n.e.k$a.call(ScalarSynchronousSingle.java:1) 
        at rx.Single.a(Single.java:17) 
        at rx.n.a.q1.a(SingleOnSubscribeMap.java:3) 
        at rx.n.a.q1.call(SingleOnSubscribeMap.java:1) 
        at rx.Single.a(Single.java:17) 
        at rx.n.a.i1.a(SingleDoOnEvent.java:3) 
        at rx.n.a.i1.call(SingleDoOnEvent.java:1) 
        at rx.Single.a(Single.java:17) 
        at rx.Single$b$a.call(Single.java:3) 
        at rx.n.c.j.run(ScheduledAction.java:2) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
2020-12-25 12:36:47.417 32175-32175/? E/RecyclerView: No adapter attached; skipping layout
2020-12-25 12:36:47.453 32175-780/? E/cm.aptoide.pt.crashreports.ConsoleLogger: Exception found
    java.lang.IllegalStateException: java.io.IOException: Connection failure
        at cm.aptoide.pt.networking.IdsRepository.b(IdsRepository.java:6)
        at cm.aptoide.pt.networking.k.call(Unknown Source:4)
        at rx.n.a.q1$a.a(SingleOnSubscribeMap.java:1)
        at rx.n.e.k$a.a(ScalarSynchronousSingle.java:1)
        at rx.n.e.k$a.call(ScalarSynchronousSingle.java:1)
        at rx.Single.a(Single.java:17)
        at rx.n.a.q1.a(SingleOnSubscribeMap.java:3)
        at rx.n.a.q1.call(SingleOnSubscribeMap.java:1)
        at rx.Single.a(Single.java:17)
        at rx.n.a.i1.a(SingleDoOnEvent.java:3)
        at rx.n.a.i1.call(SingleDoOnEvent.java:1)
        at rx.Single.a(Single.java:17)
        at rx.Single$b$a.call(Single.java:3)
        at rx.n.c.j.run(ScheduledAction.java:2)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.IOException: Connection failure
        at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(Unknown Source:73)
        at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(Unknown Source:17)
        at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(Unknown Source:47)
        at cm.aptoide.pt.networking.IdsRepository.b(IdsRepository.java:4)
        at cm.aptoide.pt.networking.k.call(Unknown Source:4) 
        at rx.n.a.q1$a.a(SingleOnSubscribeMap.java:1) 
        at rx.n.e.k$a.a(ScalarSynchronousSingle.java:1) 
        at rx.n.e.k$a.call(ScalarSynchronousSingle.java:1) 
        at rx.Single.a(Single.java:17) 
        at rx.n.a.q1.a(SingleOnSubscribeMap.java:3) 
        at rx.n.a.q1.call(SingleOnSubscribeMap.java:1) 
        at rx.Single.a(Single.java:17) 
        at rx.n.a.i1.a(SingleDoOnEvent.java:3) 
        at rx.n.a.i1.call(SingleDoOnEvent.java:1) 
        at rx.Single.a(Single.java:17) 
        at rx.Single$b$a.call(Single.java:3) 
        at rx.n.c.j.run(ScheduledAction.java:2) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: null
        at rx.n.a.q1$a.a(SingleOnSubscribeMap.java:5)
        at rx.n.e.k$a.a(ScalarSynchronousSingle.java:1) 
        at rx.n.e.k$a.call(ScalarSynchronousSingle.java:1) 
        at rx.Single.a(Single.java:17) 
        at rx.n.a.q1.a(SingleOnSubscribeMap.java:3) 
        at rx.n.a.q1.call(SingleOnSubscribeMap.java:1) 
        at rx.Single.a(Single.java:17) 
        at rx.n.a.i1.a(SingleDoOnEvent.java:3) 
        at rx.n.a.i1.call(SingleDoOnEvent.java:1) 
        at rx.Single.a(Single.java:17) 
        at rx.Single$b$a.call(Single.java:3) 
        at rx.n.c.j.run(ScheduledAction.java:2) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
2020-12-25 12:36:47.583 32175-32175/? E/cm.aptoide.pt.crashreports.ConsoleLogger: Exception found
    java.lang.IllegalStateException: java.io.IOException: Connection failure
        at cm.aptoide.pt.networking.IdsRepository.b(IdsRepository.java:6)
        at cm.aptoide.pt.networking.k.call(Unknown Source:4)
        at rx.n.a.q1$a.a(SingleOnSubscribeMap.java:1)
        at rx.n.e.k$a.a(ScalarSynchronousSingle.java:1)
        at rx.n.e.k$a.call(ScalarSynchronousSingle.java:1)
        at rx.Single.a(Single.java:17)
        at rx.n.a.q1.a(SingleOnSubscribeMap.java:3)
        at rx.n.a.q1.call(SingleOnSubscribeMap.java:1)
        at rx.Single.a(Single.java:17)
        at rx.n.a.i1.a(SingleDoOnEvent.java:3)
        at rx.n.a.i1.call(SingleDoOnEvent.java:1)
        at rx.Single.a(Single.java:17)
        at rx.Single$b$a.call(Single.java:3)
        at rx.n.c.j.run(ScheduledAction.java:2)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.IOException: Connection failure
        at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(Unknown Source:73)
        at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(Unknown Source:17)
        at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(Unknown Source:47)
        at cm.aptoide.pt.networking.IdsRepository.b(IdsRepository.java:4)
        at cm.aptoide.pt.networking.k.call(Unknown Source:4) 
        at rx.n.a.q1$a.a(SingleOnSubscribeMap.java:1) 
        at rx.n.e.k$a.a(ScalarSynchronousSingle.java:1) 
        at rx.n.e.k$a.call(ScalarSynchronousSingle.java:1) 
        at rx.Single.a(Single.java:17) 
        at rx.n.a.q1.a(SingleOnSubscribeMap.java:3) 
        at rx.n.a.q1.call(SingleOnSubscribeMap.java:1) 
        at rx.Single.a(Single.java:17) 
        at rx.n.a.i1.a(SingleDoOnEvent.java:3) 
        at rx.n.a.i1.call(SingleDoOnEvent.java:1) 
        at rx.Single.a(Single.java:17) 
        at rx.Single$b$a.call(Single.java:3) 
        at rx.n.c.j.run(ScheduledAction.java:2) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: null
        at rx.n.a.q1$a.a(SingleOnSubscribeMap.java:5)
        at rx.n.e.k$a.a(ScalarSynchronousSingle.java:1) 
        at rx.n.e.k$a.call(ScalarSynchronousSingle.java:1) 
        at rx.Single.a(Single.java:17) 
        at rx.n.a.q1.a(SingleOnSubscribeMap.java:3) 
        at rx.n.a.q1.call(SingleOnSubscribeMap.java:1) 
        at rx.Single.a(Single.java:17) 
        at rx.n.a.i1.a(SingleDoOnEvent.java:3) 
        at rx.n.a.i1.call(SingleDoOnEvent.java:1) 
        at rx.Single.a(Single.java:17) 
        at rx.Single$b$a.call(Single.java:3) 
        at rx.n.c.j.run(ScheduledAction.java:2) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by jdandrade** [comment]
We made some changes to our services related with certificates, does this issue still happen?
