### ISSUE TITLE
App just doesn't run good on flagship device

### ISSUE THREAD

**Issue by TacoTheDank** [Aptoide/aptoide-client-v8#893]
I have a Samsung Note 9 running Android Pie (Samsung's One UI).  Every time the app is opened, it's just... slow. It's much worse when the update list is clicked on. It usually doesn't even update the list when refreshing; instead, nothing happens.

I'm bad at explaining things so here's a recording: https://streamable.com/338jh

Also, please create an option to choose between displaying interstitial and banner ads. I personally don't like having my ears sexually violated by sudden super loud tiktok ads lol.

Here's one crash log from 9.6.3.0 (9533):
```
FATAL EXCEPTION: pool-20-thread-8
Process: cm.aptoide.pt, PID: 11406
java.lang.OutOfMemoryError: Failed to allocate a 65552 byte allocation with 4632 free bytes and 4KB until OOM, max allowed footprint 268435456, growth limit 268435456
	at com.android.okhttp.okio.Segment.<init>(Segment.java:62)
	at com.android.okhttp.okio.SegmentPool.take(SegmentPool.java:46)
	at com.android.okhttp.okio.Buffer.writableSegment(Buffer.java:1114)
	at com.android.okhttp.okio.InflaterSource.read(InflaterSource.java:66)
	at com.android.okhttp.okio.GzipSource.read(GzipSource.java:80)
	at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:396)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:248)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:288)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.unity3d.services.core.request.WebRequest.makeStreamRequest(WebRequest.java:190)
	at com.unity3d.services.core.request.WebRequest.makeRequest(WebRequest.java:214)
	at com.unity3d.services.core.request.WebRequestRunnable.makeRequest(WebRequestRunnable.java:68)
	at com.unity3d.services.core.request.WebRequestRunnable.run(WebRequestRunnable.java:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

I will post more logs if the app crashes more

**Comment by GustavMarwin** [comment]
Indeed, indeed. Actually I beg you to accept money for removing adds. You have this great Aptoide / Appcoins system, please, oh please, leverage it for us rich users. :-D

**Comment by jdandrade** [comment]
Hello @TacoTheDank 
Thank you very much for providing feedback. 
Our QA team will first analyse this issue to see if we can reproduce this behaviour, which didn't show up on development. As soon as we have news I will keep you posted.

@GustavMarwin I feel your pain. The roadmap for the Ads is currently in phase 1, which is testing and implementing different sources of ads and measuring the user experience. As a consequence, some flows are not fully optimised, which is something that we will tackle ASAP. 
We will tone down ads for APPC users, specially for the ones with the APPC wallet installed. I will also keep you posted on this subject.

Thank you both for the feedback.

**Comment by TacoTheDank** [comment]
@jdandrade Thanks.

@GustavMarwin That seems like a good idea.

**Comment by TacoTheDank** [comment]
Aptoide 9.6.7.0, loading the app list still lags more and more until it eventually crashes
```
FATAL EXCEPTION: glide-source-thread-4
Process: cm.aptoide.pt, PID: 4845
java.lang.OutOfMemoryError: Failed to allocate a 80 byte allocation with 32 free bytes and 32B until OOM, max allowed footprint 268435456, growth limit 268435456
	at java.util.Arrays.copyOf(Arrays.java:3260)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:451)
	at java.lang.StringBuilder.append(StringBuilder.java:137)
	at java.lang.StackTraceElement.toString(StackTraceElement.java:175)
	at java.lang.String.valueOf(String.java:2896)
	at java.lang.StringBuilder.append(StringBuilder.java:132)
	at java.lang.Throwable.printStackTrace(Throwable.java:651)
	at java.lang.Throwable.printStackTrace(Throwable.java:713)
	at android.util.Log.printlns(Log.java:544)
	at android.util.Log.e(Log.java:333)
	at com.bumptech.glide.load.engine.c.a$b$2.a(GlideExecutor.java:387)
	at com.bumptech.glide.load.engine.c.a$a$1.run(GlideExecutor.java:448)
```

**Comment by jdandrade** [comment]
We did major changes to Apps, is this still happening?

**Comment by TacoTheDank** [comment]
Ah, I forgot this issue was open. No, this issue has long since been fixed. Thanks!
